Repository Project-Easter/Flutter-UI, pull requests merged in 2021-09, with the labels that each got.

#70 close issue yml
  .github/templates/issue.md
  .github/templates/pr.md
  .github/workflows/close_issue.yml
  .github/workflows/flutter.yml
  .github/workflows/fork-sync.yml
Labels: enhancement, high-priority, experimental-feature, hacktoberfest-accepted

#71 Revamp
  assets/images/chat_placeholder.png
  lib/constants/error.dart
  lib/constants/routes.dart
  lib/main.dart
  lib/providers/books.dart
  lib/providers/user.dart
  lib/screens/add_book.dart
  lib/screens/auth/confirm_email.dart
  lib/screens/auth/forgot_password.dart
  lib/screens/auth/login.dart
  lib/screens/auth/register.dart
  lib/screens/auth/reset_password.dart
  lib/screens/book_desciption.dart
  lib/screens/bookshelf.dart
  lib/screens/chat.dart
  lib/screens/dashboard/dashboard.dart
  lib/screens/dashboard/quotes.dart
  lib/screens/home.dart
  lib/screens/initial_screen.dart
  lib/screens/more.dart
  lib/screens/profile/edit_profile.dart
  lib/screens/profile/otp_verification.dart
  lib/screens/profile/private_profile.dart
  lib/screens/profile/public_profile.dart
  lib/screens/profile/verify_mobile.dart
  lib/screens/settings_screens.dart
  lib/services/auth.dart
  lib/services/backend_services.dart
  lib/services/database_service.dart
  lib/services/user_location.dart
  lib/states/auth_state.dart
  lib/states/confirmation_code_state.dart
  lib/states/email_state.dart
  lib/states/error_state.dart
  lib/states/password_state.dart
  lib/utils/backend/auth_requests.dart
  lib/utils/backend/book_requests.dart
  lib/utils/backend/mail_request.dart
  lib/utils/backend/quote_request.dart
  lib/utils/backend/user_data_requests.dart
  lib/utils/helpers.dart
  lib/utils/router.dart
  lib/widgets/app_bar.dart
  lib/widgets/auth/auth_button.dart
  lib/widgets/auth/social_media_handles.dart
  lib/widgets/book_description/owner_info.dart
  lib/widgets/book_description/reviews.dart
  lib/widgets/button.dart
  lib/widgets/custom_navigation_bar.dart
  lib/widgets/empty_page.dart
  lib/widgets/filter_items.dart
  lib/widgets/text_field.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted

#72 Updated README.md and added CODE-OF-CONDUCT.md and CONTRIBUTING.md resolving issue number #27
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  imgs/Compare-Pull-Request.png
  imgs/Screenshot 2021-09-30 192153.png
  imgs/Screenshot 2021-09-30 193003.png
Labels: enhancement, hacktoberfest-accepted
